theme: minima
title: gerMdz y GitHub
author: GitHub Bot and Gerardo
email: gerardo.montivero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning is a passion that I nurture. It has been the best of the network to be able to have very close information to analyze, acquire and share.
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  gerMdz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
